### ISSUE TITLE
Base de dados inicial

### ISSUE THREAD

**Issue by vicenthy** [fauzihalabe/ionic-3-pizza-app#2]
Olá você teria uma base de dados inicial?

Atte.

**Comment by felipeprudencio** [comment]
Conseguiu o Db?

**Comment by fauzihalabe** [comment]
Segue pessoal, podem usar o projeto principal para se basear: 
Firebase Login: pizzaappionic@gmail.com | Pass: fKiIwxPe

**Comment by felipeprudencio** [comment]
Vlw Fauzi!

**Comment by eudanielhenrique** [comment]
Alguém criou um painel que automatiza a introdução dos dados no banco?
